{
  products(first: 24) {
    nodes {
      databaseId
      name
      onSale
      slug
      image {
        sourceUrl
      }
      ... on SimpleProduct {
        databaseId
        price
        regularPrice
        salePrice
      }
      ... on VariableProduct {
        databaseId
        price
        regularPrice
        salePrice
      }
    }
  }
}
