query Product($id: ID!) {
  product(id: $id, idType: DATABASE_ID) {
    databaseId
    averageRating
    slug
    description
    onSale
    image {
      databaseId
      uri
      title
      srcSet
      sourceUrl
    }
    name
    ... on SimpleProduct {
      price
      salePrice
      regularPrice
      databaseId
    }
    ... on VariableProduct {
      price
      salePrice
      regularPrice
      databaseId
      paColors {
        nodes {
          name
        }
      }
      paSizes {
        nodes {
          name
        }
      }
      variations {
        nodes {
          databaseId
          name
          stockStatus
          stockQuantity
          purchasable
          onSale
          salePrice
          regularPrice
        }
      }
    }
    ... on ExternalProduct {
      price
      databaseId
      externalUrl
    }
    ... on GroupProduct {
      products {
        nodes {
          ... on SimpleProduct {
            databaseId
            price
          }
        }
      }
      id
    }
  }
}
